---
title: "Politifact Analysis"
author: "Stephen Pelkofer"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports

```{r echo=FALSE, include=FALSE}
library(tidyverse)
library(ggtext)
library(ggthemes)
library(scales)
library(stringr)
library(gghighlight)
library(cowplot)
library(magick)
library(patchwork)
```

## Data

```{r}
politifact_df <- read.csv("../data/politifact_data.csv")
```


## Data Prep

```{r}
name_mappings <- tibble(
  old_nme = c("donald-trump","nancy-pelosi","joe-biden","bernie-sanders","elizabeth-warren","barack-obama"),
  clean_nme = c("Donald\n Trump","Nancy\n Pelosi","Joe\n Biden","Bernie\n Sanders","Elizabeth\n Warren","Barack\n Obama")
)

politifact_df <- left_join(politifact_df,name_mappings, by = c("Person"="old_nme"))
politifact_df$Person <- politifact_df$clean_nme

summarized_lies <- politifact_df %>%
  dplyr::mutate(Total = as.numeric(str_extract(Total,"[0-9]*")),
                Percent = as.numeric(str_extract(Percent,"[0-9]*"))/100) %>%
  group_by(Person) %>%
  mutate(All_Checks_Total = sum(Total)) %>%
  filter(Category %in% c("False", "Mostly False", "Pants on Fire")) %>%
  group_by(Person) %>%
  summarise(Percent_at_least_false = sum(Percent),
            Total = first(All_Checks_Total)) %>%
  arrange(desc(Percent_at_least_false))
summarized_lies
```

## Total Lies

```{r}
ggplot(data = summarized_lies, aes(x = reorder(Person, desc(Percent_at_least_false)),
                                   y = Percent_at_least_false)) +
  geom_bar(stat = "identity",
           fill = "#f03b20", alpha = .85,
           width = .95) +
  gghighlight(Person == "Donald\n Trump", label_key = Percent_at_least_false,
              unhighlighted_params = list(fill = alpha("#045a8d", 0.85))) +
  ylim(0,1) +
  coord_flip() +
  labs(title = "<b style='color:#252525'>Politifact Fact Checking</b>",
       subtitle = "<b style='color:#045a8d'>Democratic Leaders</b> vs. <b style='color:#f03b20'>Donald Trump</b>",
       x = element_blank(),
       y = element_blank()) +
  theme(plot.title = element_markdown(),
        plot.subtitle = element_markdown(),
        plot.caption = element_markdown(),
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major.y = element_line(color = "grey50",size = .01, linetype = "dotted"),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank())
```

## Separate Lies by Type
- Try out facet/small multiples first - this may not be best for comparison purposes
- Facet by category might work better

### Facet by Person

```{r}
lies_by_type <- politifact_df %>%
  dplyr::mutate(Total = as.numeric(str_extract(Total,"[0-9]*")),
                Percent = as.numeric(str_extract(Percent,"[0-9]*"))/100) %>%
  filter(Category %in% c("False", "Mostly False", "Pants on Fire"))

ggplot(data = lies_by_type, aes(x = Category, y = Percent, group = Category)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  facet_wrap(~Person)
```


### Stacked Bar Lies

- Need to change Mostly-False to first in order

```{r}
lies_by_type$Category <- relevel(lies_by_type$Category,"Mostly False")
```


```{r}
base_plot <- ggplot(data = lies_by_type, aes(x = reorder(Person, Percent),
                                y = Percent,
                                fill = reorder(Category,desc(Category)),
                                label = percent(Percent,1))) +
  geom_bar(position = "stack",stat = "identity",
           color = "white",
           alpha = .85,
           width = .98) +
  geom_text(aes(x = Person,
                y = Percent_at_least_false + .05,
                label = paste0(percent(Percent_at_least_false,1),", ",Total),
                fill = NULL), size = 3,
            data = summarized_lies) +
  geom_label(aes(x = 4.5, y = .73, label = "Total %, Total fact-checks"), 
             hjust = 0, 
             vjust = 0.5, 
             lineheight = 0.8,
             colour = "#252525",
             fill = "#f0f0f0",
             label.size = NA,
             size = 3) +
  geom_curve(aes(x = 4.8, y = .84, xend = 5.7, yend = .78), 
                             colour = "#252525", 
                             size=0.3, 
                             curvature = 0.2,
                             arrow = arrow(length = unit(0.03, "npc"))) +
  scale_fill_manual(values= c("#e31a1c","#fd8d3c","#fecc5c")) +
  scale_y_continuous(name="",breaks = c(0,.5,1),
                     limits=c(0, 1), labels = scales::percent) +
  coord_flip() +
  labs(title = "Compared to top Democratic Leaders, Donald Trump lies A LOT",
       subtitle = "<p style='color:#525252'>Percentage of Politifact independent fact-checks that were proved to be<br> <b style='color:#fecc5c'>Mostly False</b>, <b style='color:#fd8d3c'>False</b>, or a <b style='color:#e31a1c'>Pants-on-Fire</b>lie</p>",
       caption = "<p style='color:#252525'>Data & Images From: politifact.com | Author: Stephen Pelkofer | @Spelk24</p>",
       x = element_blank(),
       y = element_blank()) +
  theme(plot.title = element_markdown(size = 14),
        plot.subtitle = element_markdown(size = 10),
        plot.caption = element_markdown(),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())

```


```{r}
pimage <- axis_canvas(base_plot, axis = 'y') + 
  draw_image("../images/DT.png", y = .45, scale = .4, hjust = -.4) +
  draw_image("../images/NP.png", y = .27, scale = .4, hjust = -.4) +
  draw_image("../images/JB.png", y = .09, scale = .4, hjust = -.4) +
  draw_image("../images/BS.png", y = -.09, scale = .4, hjust = -.4) +
  draw_image("../images/BO.png", y = -.27, scale = .4, hjust = -.4) +
  draw_image("../images/EW.png", y = -.45, scale = .4, hjust = -.4)

StackedLies <- ggdraw(insert_yaxis_grob(base_plot, pimage, position = "left"))
StackedLies
```

## Save pngs

```{r}
ggsave(filename = "StackedLies.png",
       plot = print(StackedLies),
       width = 8,
       height = 6)
```

## Total Fact Checks

```{r}
fact_checks <- ggplot(data = summarized_lies, aes(x = reorder(Person, Total),
                                y = Total)) +
  geom_bar(position = "dodge",stat = "identity",
           color = "white",
           fill = "#023858",
           alpha = .85,
           width = .98) +
  geom_text(aes(x = Person,
                y = Total + 20,
                label = Total,
                fill = NULL), size = 3,
            data = summarized_lies) +
  ylim(0,900) +
  coord_flip() +
  labs(title = "<p style='color:#252525'>Total <b style='color:#023858'>Fact-Checks</b>",
       caption = "<p style='color:#252525'>Data From: politifact.com | Author: Stephen Pelkofer | @Spelk24</p>",
       x = element_blank(),
       y = element_blank()) +
  theme(plot.title = element_markdown(),
        plot.subtitle = element_markdown(),
        plot.caption = element_markdown(),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major.y = element_line(color = "grey50",size = .01, linetype = "dotted"),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank())

fact_checks
```

```{r}
ggsave(filename = "factchecks.png",
       plot = print(fact_checks),
       width = 7,
       height = 5)
```

